@Suppress("UnstableApiUsage")
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google {
            content {
                includeGroupByRegex("android.arch.*")
                includeGroupByRegex("androidx.*")
                includeGroupByRegex("com.android.*")
                includeGroupByRegex("com.google.*")
            }
        }

        mavenCentral {
            content {
                includeGroupByRegex("org.xerial.*")
                includeGroupByRegex("com.intellij.*")
                includeGroupByRegex("com.facebook.*")
                includeGroupByRegex("com.google.*")
                includeGroupByRegex("com.jakewharton.*")
                includeGroupByRegex("com.squareup.*")
                includeGroupByRegex("com.sun.*")
                includeGroupByRegex("jakarta.*")
                includeGroupByRegex("javax.*")
                includeGroupByRegex("net.sf.*")
                includeGroupByRegex("org.apache.*")
                includeGroupByRegex("org.jetbrains.*")
                includeGroupByRegex("org.junit.*")
                includeGroup("co.touchlab")
                includeGroup("io.coil-kt.coil3")
                includeGroup("com.airbnb.android")
                includeGroup("com.beust")
                includeGroup("com.github.javaparser")
                includeGroup("com.hannesdorfmann")
                includeGroup("com.intuit.sdp")
                includeGroup("com.thoughtworks.qdox")
                includeGroup("commons-cli")
                includeGroup("commons-codec")
                includeGroup("commons-io")
                includeGroup("commons-logging")
                includeGroup("info.picocli")
                includeGroup("io.grpc")
                includeGroup("io.reactivex.rxjava2")
                includeGroup("it.unimi.dsi")
                includeGroup("jline")
                includeGroup("net.java.dev.jna")
                includeGroup("net.ltgt.gradle.incap")
                includeGroup("org.antlr")
                includeGroup("org.bouncycastle")
                includeGroup("org.checkerframework")
                includeGroup("org.codehaus.groovy")
                includeGroup("org.glassfish")
                includeGroup("org.glassfish.jaxb")
                includeGroup("org.hamcrest")
                includeGroup("org.java-websocket")
                includeGroup("org.jvnet.staxex")
                includeGroup("org.jspecify")
                includeGroup("org.opentest4j")
                includeGroup("org.ow2.asm")
                includeGroup("org.slf4j")
                includeGroup("org.testng")
                includeGroup("org.webjars")
                includeGroup("org.reactivestreams")
                includeGroup("xerces")
                includeGroup("xml-apis")
                includeGroup("com.github.bumptech.glide")
                includeGroup("org.sonatype.oss")
                includeGroup("org.eclipse.ee4j")
                includeGroup("org.codehaus")
                includeGroup("net.java")
                includeGroup("org.ow2")

                // Detekt
                includeGroup("com.pinterest.ktlint")
                includeGroup("dev.drewhamilton.poko")
                includeGroup("io.github.davidburstrom.contester")
                includeGroup("io.github.detekt.sarif4k")
                includeGroup("io.github.microutils")
                includeGroup("io.gitlab.arturbosch.detekt")
                includeGroup("org.ec4j.core")
                includeGroup("org.jcommander")
                includeGroup("org.snakeyaml")

                // Testing
                includeGroup("app.cash.turbine")
                includeGroup("io.mockk")
                includeGroup("junit")
                includeGroup("net.bytebuddy")
                includeGroup("org.apiguardian")
                includeGroup("org.hamcrest")
                includeGroup("org.junit")
                includeGroup("org.junit.jupiter")
                includeGroup("org.junit.platform")
                includeGroup("org.mockito")
                includeGroup("org.objenesis")
                includeGroup("org.opentest4j")
                includeGroup("org.jacoco")

                // UI testing
                includeGroup("io.github.kakaocup")
                includeGroup("io.netty")
                includeGroup("io.opencensus")
                includeGroup("io.perfmark")
                includeGroup("org.ccil.cowan.tagsoup")
                includeGroup("org.codehaus.mojo")
                includeGroup("org.jsoup")
            }
        }
    }
}
